export enum UserStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  SUSPENDED = "SUSPENDED"
}

export enum SystemRole {
  SUPER_ADMIN = "SUPER_ADMIN",
  ORG_ADMIN = "ORG_ADMIN",
  HR = "HR",
  FINANCE = "FINANCE",
  DEPARTMENT_HEAD = "DEPARTMENT_HEAD",
  MANAGER = "MANAGER",
  EMPLOYEE = "EMPLOYEE",
  AUDITOR = "AUDITOR"
}

export enum TaskStatus {
  DRAFT = "DRAFT",
  ASSIGNED = "ASSIGNED",
  ACCEPTED = "ACCEPTED",
  IN_PROGRESS = "IN_PROGRESS",
  SUBMITTED = "SUBMITTED",
  IN_REVIEW = "IN_REVIEW",
  CHANGES_REQUESTED = "CHANGES_REQUESTED",
  RESUBMITTED = "RESUBMITTED",
  APPROVED = "APPROVED",
  CLOSED = "CLOSED"
}

export enum TaskPriority {
  CRITICAL = "CRITICAL",
  HIGH = "HIGH",
  MEDIUM = "MEDIUM",
  LOW = "LOW"
}

export enum LeaveType {
  SICK = "SICK",
  CASUAL = "CASUAL",
  EARNED = "EARNED",
  WFH = "WFH",
  HALF_DAY = "HALF_DAY"
}

export enum LeaveStatus {
  PENDING = "PENDING",
  MANAGER_APPROVED = "MANAGER_APPROVED",
  HR_APPROVED = "HR_APPROVED",
  REJECTED = "REJECTED",
  CANCELLED = "CANCELLED"
}

export enum AttendanceStatus {
  PRESENT = "PRESENT",
  ABSENT = "ABSENT",
  LATE = "LATE",
  HALF_DAY = "HALF_DAY",
  ON_LEAVE = "ON_LEAVE"
}

export enum PayrollStatus {
  DRAFT = "DRAFT",
  GENERATED = "GENERATED",
  APPROVED = "APPROVED",
  PAID = "PAID"
}

export enum ExpenseStatus {
  DRAFT = "DRAFT",
  SUBMITTED = "SUBMITTED",
  MANAGER_APPROVED = "MANAGER_APPROVED",
  FINANCE_APPROVED = "FINANCE_APPROVED",
  PAID = "PAID",
  REJECTED = "REJECTED"
}

export enum AssetStatus {
  AVAILABLE = "AVAILABLE",
  ASSIGNED = "ASSIGNED",
  DAMAGED = "DAMAGED",
  RETIRED = "RETIRED"
}

export enum NotificationType {
  TASK_ASSIGNED = "TASK_ASSIGNED",
  TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED",
  LEAVE_APPLIED = "LEAVE_APPLIED",
  LEAVE_APPROVED = "LEAVE_APPROVED",
  LEAVE_REJECTED = "LEAVE_REJECTED",
  SALARY_GENERATED = "SALARY_GENERATED",
  EXPENSE_APPROVED = "EXPENSE_APPROVED",
  ASSET_ASSIGNED = "ASSET_ASSIGNED",
  REVIEW_DUE = "REVIEW_DUE",
  SYSTEM = "SYSTEM"
}

export enum AuditAction {
  CREATED = "CREATED",
  UPDATED = "UPDATED",
  DELETED = "DELETED",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  STATUS_CHANGED = "STATUS_CHANGED",
  LOGIN = "LOGIN",
  LOGOUT = "LOGOUT",
  PERMISSION_DENIED = "PERMISSION_DENIED"
}

export enum RoleScope {
  ORG = "ORG",
  DEPARTMENT = "DEPARTMENT",
  TEAM = "TEAM"
}
