export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 10,
  MAX_LIMIT: 100
};

export const JWT = {
  ACCESS_ALGORITHM: "HS256" as const,
  REFRESH_ALGORITHM: "HS256" as const
};

export const TASK_STATE = {
  DRAFT: "DRAFT",
  ASSIGNED: "ASSIGNED",
  ACCEPTED: "ACCEPTED",
  IN_PROGRESS: "IN_PROGRESS",
  SUBMITTED: "SUBMITTED",
  IN_REVIEW: "IN_REVIEW",
  CHANGES_REQUESTED: "CHANGES_REQUESTED",
  RESUBMITTED: "RESUBMITTED",
  APPROVED: "APPROVED",
  CLOSED: "CLOSED"
} as const;

export const TASK_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ["ASSIGNED", "ACCEPTED", "IN_PROGRESS", "SUBMITTED", "CLOSED"],
  ASSIGNED: ["ACCEPTED", "IN_PROGRESS", "SUBMITTED", "DRAFT", "CLOSED"],
  ACCEPTED: ["IN_PROGRESS", "SUBMITTED", "CLOSED"],
  IN_PROGRESS: ["SUBMITTED", "CLOSED", "ACCEPTED"],
  SUBMITTED: ["IN_REVIEW", "CLOSED", "ACCEPTED", "IN_PROGRESS"],
  IN_REVIEW: ["APPROVED", "CHANGES_REQUESTED", "CLOSED", "ACCEPTED", "IN_PROGRESS"],
  CHANGES_REQUESTED: ["RESUBMITTED", "CLOSED", "ACCEPTED", "IN_PROGRESS"],
  RESUBMITTED: ["IN_REVIEW", "CLOSED", "ACCEPTED", "IN_PROGRESS"],
  APPROVED: ["CLOSED", "ACCEPTED", "IN_PROGRESS"],
  CLOSED: ["DRAFT", "ASSIGNED", "ACCEPTED", "IN_PROGRESS"]
};

